# Generated by Django 2.1.7 on 2019-02-15 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
